export default {
  API_ADDRESS: process.env.REACT_APP_API_URL,
  WS_ADDRESS: process.env.REACT_APP_WS_URL,
  HYDRO_PROXY_ADDRESS: process.env.REACT_APP_HYDRO_PROXY_ADDRESS,
  HYDRO_TOKEN_ADDRESS: process.env.REACT_APP_HYDRO_TOKEN_ADDRESS
};
