export default {
  API_ADDRESS: process.env.REACT_APP_API_ADDRESS,
  WS_ADDRESS: process.env.REACT_APP_WS_ADDRESS,
  HYDRO_PROXY_ADDRESS: process.env.REACT_APP_HYDRO_PROXY_ADDRESS,
  HOT_CONTRACT_ADDRESS: process.env.REACT_APP_HOT_CONTRACT_ADDRESS
};
