FROM node:11.10.0 AS builder

ARG REACT_APP_API_URL
ARG REACT_APP_WS_URL
ARG REACT_APP_HYDRO_PROXY_ADDRESS
ARG REACT_APP_HYDRO_TOKEN_ADDRESS

ENV REACT_APP_API_URL ${REACT_APP_API_URL}
ENV REACT_APP_WS_URL ${REACT_APP_WS_URL}
ENV REACT_APP_HYDRO_PROXY_ADDRESS ${REACT_APP_HYDRO_PROXY_ADDRESS}
ENV REACT_APP_HYDRO_TOKEN_ADDRESS ${REACT_APP_HYDRO_TOKEN_ADDRESS}

COPY . /app
WORKDIR /app
RUN yarn install
RUN yarn run build

FROM wlchn/gostatic:latest
ENV CONFIG_FILE_PATH /srv/http
COPY --from=builder /app/build /srv/http
COPY ./env.sh /env.sh
ENTRYPOINT ["sh", "/env.sh"]
CMD ["/goStatic"]