version: "3"
volumes:
  datavolume: {}
services:
  web:
    build:
      context: .
      args:
        - CONFIG_VARS=REACT_APP_API_URL,REACT_APP_WS_URL,REACT_APP_HYDRO_PROXY_ADDRESS,REACT_APP_HYDRO_TOKEN_ADDRESS
        - REACT_APP_API_URL=http://localhost:3001
        - REACT_APP_WS_URL=ws://localhost:3002
        - REACT_APP_HYDRO_PROXY_ADDRESS=0x04f67e8b7c39a25e100847cb167460d715215feb
        - REACT_APP_HYDRO_TOKEN_ADDRESS=0x4c4fa7e8ea4cfcfc93deae2c0cff142a1dd3a218
    container_name: hydro-sdk-web
    ports:
      - 3000:8043
    restart: on-failure:5